insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (1, 'Sisely MacCaffery','2025-06-14', 'The spaghetti was really good', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (2, 'Billie Nyssens', '2025-05-12', 'I really like the iced coffee they served, it is not too sweet yet not bitter', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (3, 'Paul O''Glassane', '2024-03-21', 'The steak was absolutely delicious', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (4, 'Susanetta Frew', '2025-04-30', 'The carbonara was perfectly creamy', 4);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (5, 'Saunder De Ruggero', '2025-03-18', 'Chocolate brownie did not taste fresh', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (6, 'Jacki Sawter', '2025-02-09', 'Iced coffee was just decent', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (7, 'Norrie Izhak', '2025-01-26', 'Fettucine carbonara was perfectly cooked', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (8, 'Edwin Paddeley', '2024-12-15', 'The steak was absolutely delicious', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (9, 'Avictor Caff', '2024-11-20', 'Best picanha steak I have had in a while', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (10, 'Ado Musslewhite', '2024-11-05', 'Wouldnt order the French fries again', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (11, 'Geoffrey Plows', '2024-10-12', 'Grilled salmon was perfectly cooked', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (12, 'Jeannette Stoddard', '2024-10-01', 'The spaghetti bolognese was okay, nothing special', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (13, 'Viviene Crees', '2024-09-14', 'I really loved the chocolate brownie', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (14, 'Paten Prazer', '2024-09-02', 'The iced tea tasted average', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (15, 'Cicely Dominey', '2024-08-27', 'The picanha steak exceeded my expectations', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (16, 'Patrizio Aleshkov', '2024-08-09', 'French fries were underwhelming', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (17, 'Fabe Rauprich', '2024-07-29', 'The grilled salmon was absolutely delicious', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (18, 'Rad Vobes', '2024-07-10', 'Spaghetti bolognese tasted average', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (19, 'Leeland Fortey', '2024-06-21', 'I was disappointed by the iced coffee', 1);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (20, 'Town Jumonet', '2024-06-02', 'Best fries Ive had in a while', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (21, 'Brod McDavitt', '2024-05-18', 'The chocolate brownie exceeded my expectations', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (22, 'Liv Gillino', '2024-05-05', 'Wouldnt order the spaghetti bolognese again', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (23, 'Noland Ferryn', '2024-04-26', 'Fettucine carbonara was perfectly cooked', 4);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (24, 'Ilyssa Sterte', '2024-04-12', 'The iced tea was okay, nothing special', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (25, 'Ilsa Knell', '2024-03-23', 'Picanha steak did not taste fresh', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (26, 'Rooney Warlock', '2024-03-10', 'French fries were perfectly cooked', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (27, 'Gianina Blunn', '2024-02-27', 'Iced coffee tasted average', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (28, 'Viva Shelliday', '2024-02-15', 'I was disappointed by the grilled salmon', 1);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (29, 'Bette Colson', '2024-02-01', 'Spaghetti bolognese was perfectly cooked', 4);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (30, 'Sallyann Shevill', '2024-01-20', 'Best iced coffee Ive had in a while', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (31, 'Cesya Robart', '2024-01-06', 'Chocolate brownie was underwhelming', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (32, 'Lucas Maytom', '2023-12-22', 'Iced tea exceeded my expectations', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (33, 'Fair Cason', '2023-12-09', 'Fettucine carbonara tasted average', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (34, 'Mellicent Brommage', '2023-11-30', 'French fries were absolutely delicious', 4);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (35, 'Ferdinanda Figura', '2023-11-18', 'Grilled salmon was underwhelming', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (36, 'Filberte Kapelhof', '2023-11-04', 'Spaghetti bolognese exceeded my expectations', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (37, 'Kendell Mundell', '2023-10-19', 'I really loved the iced coffee', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (38, 'Zulema Robbs', '2023-10-01', 'Chocolate brownie tasted average', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (39, 'Herc Hinsch', '2023-09-17', 'The coffee was too sweet', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (40, 'Spencer Kolushev', '2023-09-02', 'Iced tea was perfectly brewed', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (41, 'Marsiella De Ambrosis', '2023-08-20', 'Best French fries Ive had in a while', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (42, 'Lani Brinsden', '2023-08-05', 'I was disappointed by the grilled salmon', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (43, 'Darnall Cordeux', '2023-07-23', 'Fettucine carbonara was absolutely delicious', 4);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (44, 'Filippa Petticrow', '2023-07-09', 'The iced coffee was okay, nothing special', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (45, 'Tomas Abbet', '2023-06-26', 'Chocolate brownie exceeded my expectations', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (46, 'Leroi Swannie', '2023-06-11', 'Spaghetti bolognese tasted average', 3);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (47, 'Magnum Danbye', '2023-05-30', 'Wouldnt order the iced tea again', 2);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (48, 'Fredia Croft', '2023-05-15', 'French fries were perfectly cooked', 4);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (49, 'Cheslie Cocci', '2023-05-01', 'Grilled salmon exceeded my expectations', 5);
insert into `CustomerReview` (review_id, reviewer_name, review_date, review_text, rate) values (50, 'Eydie Clemon', '2023-04-17', 'Iced coffee tasted average', 3);
-- …continue similarly up to review_id 100 with realistic names…
